const regionsRus = [
  {rus:'Алтай', EN:'Altay'},
  {rus:'Алтайский край', EN:'Altaysky Kray'},
  {rus:'Амурская область', EN:'Amurskaya Oblast'},
  {rus:'Архангельская область', EN:'Arhangelskaya Oblast'},
  {rus:'Астраханская область', EN:'Astrahanskaya Oblast'},
  {rus:'Республика Башкортостан', EN:'Bashkortostan'},
  {rus:'Белгородская область', EN:'Belgorodskaya Oblast'},
  {rus:'Брянская область', EN:'Bryanskaya Oblast'},
  {rus:'Республика Бурятия', EN:'Buryatiya'},
  {rus:'Владимирская область', EN:'Vladimirskaya Oblast'},
  {rus:'Волгоградская область', EN:'Volgogradskaya Oblast'},
  {rus:'Вологодская область', EN:'Vologodskaya Oblast'},
  {rus:'Воронежская область', EN:'Voronejskaya Oblast'},
  {rus:'Москва', EN:'Moskva'},
  {rus:'Санкт-Петербург', EN:'Sankt Peterburg'},
  {rus:'Еврейская автономная область', EN:'Evreyskaya AO'},
  {rus:'Забайкальский край', EN:'Zabaykalsky Kray'},
  {rus:'Ивановская область', EN:'Ivanovskaya Oblast'},
  {rus:'Республика Ингушения', EN:'Ingushetiya'},
  {rus:'Иркутская область', EN:'Irkutskaya Oblast'},
  {rus:'Кабардино-Балкарская Республика', EN:'Kabardino Balkariya'},
  {rus:'Калининградская область', EN:'Kaliningradskaya Oblast'},
  {rus:'Калужская область', EN:'Kalujskaya Oblast'},
  {rus:'Камчатский край', EN:'Kamchatsky Kray'},
  {rus:'Карачаево-Черкесская Республика', EN:'Karachaevo Cherkessiya'},
  {rus:'Кемеровская область', EN:'Kemerovskaya Oblast'},
  {rus:'Кировская область', EN:'Kirovskaya Oblast'},
  {rus:'Костромская область', EN:'Kostromskaya Oblast'},
  {rus:'Краснодарский край', EN:'Krasnodarsky Kray'},
  {rus:'Красноярский край', EN:'Krsanoyarsky Kray'},
  {rus:'Республика Крым', EN:'Krym'},
  {rus:'Курганская область', EN:'Kurganskaya Oblast'},
  {rus:'Курская область', EN:'Kurskaya Oblast'},
  {rus:'Ленинградская область', EN:'Leningradskaya Oblast'},
  {rus:'Липецкая область', EN:'Lipetckaya Oblast'},
  {rus:'Магаданская область', EN:'Magadanskaya Oblast'},
  {rus:'Московская область', EN:'Moskovskaya Oblast'},
  {rus:'Мурманская область', EN:'Murmanskaya Oblast'},
  {rus:'Ненецкий автономный округ', EN:'Nenecky AO'},
  {rus:'Нижегородская область', EN:'Nijegorodskaya Oblast'},
  {rus:'Новгородская область', EN:'Novgorodskaya Oblast'},
  {rus:'Новосибирская область', EN:'Novosibirskaya Oblast'},
  {rus:'Омская область', EN:'Omskaya Oblast'},
  {rus:'Оренбургская область', EN:'Orenburgskaya Oblast'},
  {rus:'Орловская область', EN:'Orlovskaya Oblast'},
  {rus:'Пензенская область', EN:'Penzenskaya Oblast'},
  {rus:'Пермский край', EN:'Permsky Kray'},
  {rus:'Приморский край', EN:'Primorsky Kray'},
  {rus:'Псковская область', EN:'Pskovskaya Oblast'},
  {rus:'Республика Адыгея', EN:'Adygeya'},
  {rus:'Республика Дагестан', EN:'Dagestan'},
  {rus:'Республика Калмыкия', EN:'Kalmykiya'},
  {rus:'Республика Карелия', EN:'Kareliya'},
  {rus:'Республика Коми', EN:'Komy'},
  {rus:'Республика Марий Эл', EN:'Mary ell'},
  {rus:'Республика Мордовия', EN:'Mordoviya'},
  {rus:'Республика Саха (Якутия)', EN:'Yakutiya'},
  {rus:'Республика Северная Осетия — Алания', EN:'Severnaya Osetiya'},
  {rus:'Республика Татарстан', EN:'Tatarstan'},
  {rus:'Республика Тыва', EN:'Tyva'},
  {rus:'Республика Хакасия', EN:'Hakasiya'},
  {rus:'Ростовская область', EN:'Rostovskaya Oblast'},
  {rus:'Рязанская область', EN:'Ryazanskaya Oblast'},
  {rus:'Самарская область', EN:'Samarskaya Oblast'},
  {rus:'Саратовская область', EN:'Saratovslaya Oblast'},
  {rus:'Сахалинская область', EN:'Sahalinskaya Oblast'},
  {rus:'Свердловская область', EN:'Sverdlovskaya Oblast'},
  {rus:'Севастополь', EN:'Sevastopol'},
  {rus:'Смоленская область', EN:'Smolenskaya Oblast'},
  {rus:'Ставропольский край', EN:'Stavropolsky Kray'},
  {rus:'Тамбовская область', EN:'Tambovskaya Oblast'},
  {rus:'Тверская область', EN:'Tverskaya Oblast'},
  {rus:'Томская область', EN:'Tomskaya Oblast'},
  {rus:'Тульская область', EN:'Tulskaya Oblast'},
  {rus:'Тюменская область', EN:'Tumenskaya Oblast'},
  {rus:'Удмуртская Республика', EN:'Udmurtiya'},
  {rus:'Ульяновская область', EN:'Ulyanovskaya Oblast'},
  {rus:'Хабаровский край', EN:'Habarovsky Kray'},
  {rus:'Ханты-Мансийский автономный округ', EN:'HMAO'},
  {rus:'Челябинская область', EN:'Chelyabinskaya Oblast'},
  {rus:'Чеченская Республика', EN:'Checnya'},
  {rus:'Чувашская Республика', EN:'Chuvashiya'},
  {rus:'Чукотский автономный округ', EN:'Chukotsky AO'},
  {rus:'Ямало-Ненецкий автономный округ', EN:'YANAO'},
  {rus:'Ярославская область', EN:'Yaroslavskaya Oblast'}
]

export default regionsRus